### ISSUE TITLE
expression evaluation test on JDK 11

### ISSUE THREAD

**Issue by svrahul** [soulwing/pinject#13]
Cannot trace why, but the functionality for the @Property("#{e:required('PATH')} in FieldInjectionTargetBean seems to be fetching the PATH correctly. But the test fails because the SDK does not consider this expression as Literal text (without escape characters.

Therefore this test case in PropertyInjectionExtensionTest alone fails:

    assertThat(bean.path, is(not(nullValue())));
    System.out.println(bean.path);
 (Lines 68 and 69)

For now, I am just forking and commenting the troublesome parts and movin forward. But perhaps, you can fix it if you know exactly why the PATH output does not have double slashes (escapes) or if the isLiteralText() method in org.soulwing.cdi.properties.extension.ELExpressionEvaluator 's line 112 blows off. Here is that block:

     if (!ve.isLiteralText()) {
        throw new UnresolvedExpressionException(
            "expression contains unresolved values: " +  expression + " => " + value);
      }

**Comment by svrahul** [comment]
Thanks for the great work BTW!!! Lean and quite functional!!

**Comment by ceharris** [comment]
Interesting -- it doesn't fail for me on JDK 11.

What operating system?

**Comment by ceharris** [comment]
I'd be interested to see what's in the PATH that is failing to evaluate as literal text, too.

Ideally the test case would use an environment variable designated for the test, but that's a bit difficult to arrange in Java since it provides no mechanism to copy and modify the environment it inherits from the OS when it executes.

**Comment by ceharris** [comment]
Just to experiment, I added this test. With the given string (which seems like a pretty common Windows path construct), `isLiteralText` returns false.  :-/

```
  @Test
  public void test() throws Exception {
    ExpressionFactory expressionFactory = ExpressionFactory.newInstance();
    ELContext context = new StandardELContext(expressionFactory);
    assertThat(expressionFactory.createValueExpression(context,
        "\\windows\\style\\path", String.class).isLiteralText(), is(false));
  }
```

It's really just a sanity check, anyway. Guess it needs to log a warning instead of throwing an exception.

**Comment by ceharris** [comment]
I changed it from throwing to logging a warning. Let me know how that works out for you. Assuming it works, I'll push a new release to standard maven repos.
