### ISSUE TITLE
Add ability to define regex in properties file

### ISSUE THREAD

**Issue by mikesir87** [soulwing/pinject#9]
PR #8 provides the converter support, but it looks like the value in the converter has all backslashes removed, which makes defining regex patterns a little difficult.  Haven't been successful with single or double slashes.  Not sure where to look quite yet...

**Comment by ceharris** [comment]
The Properties.load method does who-knows-what to the property values.

**Comment by ceharris** [comment]
Could start there in a debugger to see what's getting loaded.

**Comment by mikesir87** [comment]
When using double-slashes **test-(\w+)**, it comes out as **test-(\w+)** right after the property loading, which is what I would expect.  So... double back-slash gets reduced down to one.

I wonder... could the EL resolving be playing into it?  I'll try to spend a few more mins later tonight looking at it.

**Comment by ceharris** [comment]
I added some tests for `ELExpressionEvaluator` when a property value has escape sequences. Seems to work as expected. Those tests are on master.

**Comment by ceharris** [comment]
Narrows it down a bit.

```
FINEST: injecting into [BackedAnnotatedField] @Inject @Property public org.soulwing.cdi.properties.extension.FieldInjectionTargetBean.pattern
Sep 21, 2016 4:35:39 AM org.soulwing.cdi.properties.extension.DelegatingPropertyValueResolver resolve
FINE: resolved org.soulwing.cdi.properties.extension.FieldInjectionTargetBean.pattern=\s*hello\s* (MetaInfBeanPropertiesResolver)
Sep 21, 2016 4:35:39 AM org.soulwing.cdi.properties.extension.SimplePropertyBeanContainer add
FINE: created property bean: org.soulwing.cdi.properties.extension.FieldInjectionTargetBean.pattern=`s*hellos*` for injection point [BackedAnnotatedField] @Inject @Property public org.soulwing.cdi.properties.extension.FieldInjectionTargetBean.pattern
```

**Comment by ceharris** [comment]
The good news is that I found the issue and there is a workaround. The bad news is that this is not something that can be easily fixed. My first EL tests were focused on resolving properties using `${p:required}`. But in fact _every_ string property value is evaluated as an EL expression, so even a property value like `hello` or (more to the point) `\\w+` is evaluated as an expression. This allows property references embedded in string values to work; e.g. `hello ${p:required('name')}`.

Because of this, there are actually two rounds of escape sequence processing happening; one by `Properties.load` and the other by the EL expression evaluation. Doubling up the backslash allows one backslash to survive the first round. So you can probably guess that the workaround is to double up again. The _oh-so-delightfully-intuitive_ expression `\\\\w+` ends up being `\w+` when both rounds of evaluation are finished. Enjoy!

**Comment by ceharris** [comment]
The real fix for this involves replacing Properties.load with an alternative that processes escape sequences (for things like line continuation and keys that contain `:` or `=`) but doesn't remove the other escape sequences allowing EL to do that instead. That'll be lots of fun to write.

**Comment by mikesir87** [comment]
After applying the workaround of using `\\\\w+`, I know get the following exception during deploy, where `MyBean.pattern` is a String.

```
Caused by: org.soulwing.cdi.properties.extension.UnresolvedExpressionException: failed to resolve value for 'MyBean.pattern': expression contains unresolved values: test-(\\\\w+) => test-(\\w+)
        at org.soulwing.cdi.properties.extension.SimplePropertyBeanContainer.resolve(SimplePropertyBeanContainer.java:211)
        at org.soulwing.cdi.properties.extension.SimplePropertyBeanContainer.add(SimplePropertyBeanContainer.java:107)
        at org.soulwing.cdi.properties.extension.PropertyInjectionExtension.processInjectionPoint(PropertyInjectionExtension.java:114)
        at sun.reflect.GeneratedMethodAccessor185.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
```

**Comment by mikesir87** [comment]
Looks like the issue is occurring in the `ElExpressionEvaluator` when it's doing the last `expressionFactory.createValueExpression` and looking for `!ve.isLiteralText()`.  

If the initial property is double-escaped (`test-(\\\\w+)`), the value of `value` is `test-(\w+)` when going into the second `expressionFactory.createValueExpression`.  For some reason, it thinks that `test-(\w+)` is not literal text, which then causes the exception.

The problem is that the value of `test-(\w+)` is what I want to be injected, so I can't simply double-escape everything again.  But, `test-(\\w+)` is what needs to be used for the last `expressionFactory.createValueExpression`.

For kicks, I made the following modification... 

``` java
ve = expressionFactory.createValueExpression(context, value.replaceAll("\\\\", "\\\\\\\\"), String.class);
```

That then let the literal text test pass and then caused the right thing to be injected (when using `test-(\\\\w+)` as the value in the property file.
